### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by mimoccc** [femto-email/client#31]
Well, this server is hard to run due dependencies are obsolete and some of system dependencies missing.
After many many bugs to be fixed it ends with error if started as root for electron package.
Is project still alive?
Looks cool :)

**Comment by popey456963** [comment]
Hey, sorry.  This project is exceptionally old now and I'm not surprised dependencies are missing, etc.  It's a good project to look to see how we solved various IMAP issues and for educational usage, but not suitable for actually running as an email client.
