### ISSUE TITLE
When maximised, the window overflows

### ISSUE THREAD

**Issue by pbexe** [femto-email/client#6]
Some of the title bar is hidden when the window is maximised. Could be a problem with electron?

**Comment by popey456963** [comment]
You getting this too you mean?  Not just me?

**Comment by popey456963** [comment]
Electron issue electron/electron#5267  
Fixed in pull request electron/electron#9167 (13/04/2017)  
We'll just need to wait until it arrives in a stable Electron build, which will likely be in a week or two.

**Comment by popey456963** [comment]
Leaving this open until they do actually release an updated build so that we remember to change the `package.json` version.

**Comment by popey456963** [comment]
Closing as it is fixed in V1.6.7 (still in beta).
